from __future__ import annotations

class Signal:
    def emit(self, *values: object) -> None: ...
    def connect(self, handler: object) -> None: ...

def signal(*types: object) -> Signal: ...

class Node:
    node_path: str
    def get_node(self, path: str) -> NodeProxy: ...
    def _ready(self) -> None: ...
    def _process(self, delta: float) -> None: ...

class NodeProxy:
    position: tuple[float, float]
    text: str

def held(key: str) -> bool: ...
def pressed(key: str) -> bool: ...
def released(key: str) -> bool: ...
def mouse() -> tuple[float, float]: ...

class Node2D(Node):
    position: tuple[float, float]

class Sprite2D(Node2D):
    texture: str

class Camera2D(Node2D): ...

class Timer(Node):
    wait_time: float

class Label(Node):
    text: str
