from __future__ import annotations

class Node:
    def get_node(self, path: str) -> Node: ...
    def _ready(self) -> None: ...
    def _process(self, delta: float) -> None: ...

class Node2D(Node):
    position: tuple[float, float]

class Sprite2D(Node2D):
    texture: str

class Camera2D(Node2D): ...
class Timer(Node): ...
